; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D I2C_SDA_PIN=21
    -D I2C_SCL_PIN=22
    -D I2C_CLOCK_HZ=100000
